# Generated by Django 4.1.7 on 2023-03-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydesignitem',
            old_name='disign_code',
            new_name='design_code',
        ),
        migrations.AlterField(
            model_name='mydesignitem',
            name='designer',
            field=models.CharField(max_length=20),
        ),
    ]
