# Generated by Django 4.1.7 on 2023-03-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0002_rename_disign_code_mydesignitem_design_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydesignitem',
            name='description',
        ),
    ]
