# Generated by Django 4.1.7 on 2023-03-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0003_remove_mydesignitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydesignitem',
            name='img',
            field=models.TextField(blank=True),
        ),
    ]
