# Generated by Django 4.1.7 on 2023-03-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0005_alter_mydesignitem_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydesignitem',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='mydesignitem',
            name='img',
            field=models.TextField(blank=True, default='https://izapislewska.weebly.com/uploads/4/9/8/6/49862713/custom-design_orig.png'),
        ),
    ]
